"""Write the Windows version resource PyInstaller stamps into the exe.

    python tools\\make_version.py build\\version_info.txt

This is the thing the file's Properties dialog reads, and the name Task Manager,
UAC and SmartScreen show for the process. Generated rather than checked in, so
it cannot drift away from cutemute/__init__.py.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from cutemute import (APP_NAME, COPYRIGHT, DESCRIPTION, PUBLISHER,  # noqa: E402
                      __version__)

TEMPLATE = '''# Generated by tools/make_version.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=%(numbers)s,
    prodvers=%(numbers)s,
    mask=0x3f,
    flags=0x0,
    OS=0x40004,          # VOS_NT_WINDOWS32
    fileType=0x1,        # VFT_APP
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        # US English, Unicode: what makes the Language row read "English
        # (United States)" instead of sitting there empty.
        '040904B0',
        [StringStruct('CompanyName', %(publisher)r),
         StringStruct('FileDescription', %(name)r),
         StringStruct('FileVersion', %(version)r),
         StringStruct('InternalName', %(name)r),
         StringStruct('LegalCopyright', %(copyright)r),
         StringStruct('OriginalFilename', %(filename)r),
         StringStruct('ProductName', %(name)r),
         StringStruct('ProductVersion', %(version)r),
         StringStruct('Comments', %(description)r)]),
    ]),
    VarFileInfo([VarStruct('Translation', [0x0409, 1200])]),
  ],
)
'''


def numbers(version):
    """'1.0.0' -> (1, 0, 0, 0): the resource wants exactly four parts."""
    parts = [int(part) for part in version.split(".")]
    return tuple((parts + [0, 0, 0, 0])[:4])


def build(path):
    quad = numbers(__version__)
    text = TEMPLATE % {
        "numbers": quad,
        "version": ".".join(str(part) for part in quad),
        "name": APP_NAME,
        "publisher": PUBLISHER,
        "copyright": COPYRIGHT,
        "description": DESCRIPTION,
        "filename": "%s.exe" % APP_NAME,
    }
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print("wrote %s (%s %s, %s)" % (out, APP_NAME, __version__, PUBLISHER))


if __name__ == "__main__":
    build(sys.argv[1] if len(sys.argv) > 1 else "build/version_info.txt")
